= Review - Data Structures
:sourcedir: /Users/curri/IntroJava/Samples/src/main/java/okaram/notes
:source-highlighter: pygments

== Linear Data Structures

* By Implementation
    ** Linked list
    ** Vector
* By use
    ** Stack
    ** Queue
    ** Dequeue
    ** Priority queue is implemented with tree-like structures

=== Linked lists

Used to implement linear structures (like arrays). Each node contains the actual data, and a pointer/reference to the next node in the list. The list is just a pointer to the head of the list (the first node).

==== Variations:
* Single linked list (normal)
* Doubly linked list (node contains pointer to previous, next)
    ** Circular - last node points to the head too
* List could also keep a pointer to last element, to facilitate inserting at the end.
* Skip lists - keep pointers to elements in the middle, to have logarithmic access time

=== Efficiency
* Extra memory, one pointer per element 
* Extra allocations, loses locality of reference
* Insert (at front) - O(1)
* get - O(n) n being the index
 
=== Sample code
[source,java]
----
class LinkedList<T> {
    private static class Node<T> {
        T data;
        Node<T> next;
    }
    Node<T> head;
}
----

==== aside - recursion
Most linked list algorithms can be done without recursion, using while loops; but many times recursion makes it easier :). Many tree algorithms use recursion.

[source,java]
----
    private static int nodeSize(Node currentHead) {
        if(currentHead==null)
            return 0;
        return 1+nodeSize(currentHead.next);
    }

    public int size() {
        return nodeSize(head);
    }
----


=== Vectors
Vectors are thin wrappers against arrays; we allocate an array, with extra spaces; keep track of the actual number of elements; if we run out of extra spaces, we need to copy the array.


=== Stack
Stacks support only two operations, push and pop (well, and top, size). Stacks are Last In First Out (LIFO).

Implementing a stack is easy, either with a vector or linked list, since insertions and deletions are from the same side (push,pop).

=== Queue, Circular queue

=== Priority queues and heaps

Heaps are binary-tree-like structures, where the root is always less (for min heaps) than its two children, but there is no ordering between the children. 

Heaps are also compact (we fill all the levels first, and we fill leaves in left-to-right order), so they can be stored in an array, with no extra space. The children of node i are node 2*i+1 and 2*i+2 (if we start at 0).

== Trees

== Searching structures

* Binary Search Trees
    ** Balancing
        *** 2-3 Trees
        *** Red-Black Trees
        *** AVL Trees
* Hash tables
* Multidimensional trees, tables
